
# 阿里云 redis集群后，后台总是重定向到阿里云内网 导致超时连接
#spring:
#  redis:
#    # 集群（分片）模式
#    cluster:
#      max-redirects: 3
#      #节点
#      nodes:
#        - 120.79.161.30:6379
#        - 120.79.161.30:6380
#        - 120.79.161.30:6381
#        - 120.79.161.30:6382
#        - 120.79.161.30:6383
#        - 120.79.161.30:6384
#    # Redis服务器连接密码（默认为空）
#    password:
#    #jedis连接池信息仅供参考
#    lettuce:
#      pool:
#        #连接池最大连接数（使用负值表示没有限制）
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#        # 连接池中的最大空闲连接
#        pool.max-idle: 8
#        # 连接池中的最小空闲连接
#        pool.min-idle: 0
